FROM mhart/alpine-node:9
RUN apk add --update \
    python \
    python-dev \
    py-pip \
    build-base \
    && rm -rf /var/cache/apk/* \
    && pip install awscli
RUN apk upgrade --update && apk add  --no-cache --virtual .build-deps \
  curl \
  yarn \
  git \
  zip
