export const SET_OFFERS = 'SET_OFFERS'
export const SET_FAVORITE_OFFERS = 'SET_FAVORITE_OFFERS'
export const FAVORITE_OFFER = 'FAVORITE_OFFER'
export const REMOVE_FAVORITE_OFFER = 'REMOVE_FAVORITE_OFFER'

export const SET_BUSINESS_DETAILS = 'SET_BUSINESS_DETAILS'
export const CREATE_BUSINESS = 'CREATE_BUSINESS'
export const FETCH_BUSINESS_DETAILS = 'FETCH_BUSINESS_DETAILS'
export const FETCH_BUSINESS_AUDIENCES = 'FETCH_BUSINESS_AUDIENCES'
export const FETCH_BUSINESS_LIST = 'FETCH_BUSINESS_LIST'
export const UPDATE_BUSINESS_INFO = 'UPDATE_BUSINESS_INFO'

export const FETCH_INFLUENCER_BALANCE = 'FETCH_INFLUENCER_BALANCE'
export const FETCH_INFLUENCER_SUMMARY = 'FETCH_INFLUENCER_SUMMARY'

export const FETCH_DB_ENUMS = 'FETCH_DB_ENUMS'

export const RECOMMEND_CAMPAIGN = 'RECOMMEND_CAMPAIGN'
export const UPDATE_CAMPAIGN = 'UPDATE_CAMPAIGN'
export const CREATE_CAMPAIGN = 'CREATE_CAMPAIGN'
export const UPDATE_CAMPAIGN_RESULTS = 'UPDATE_CAMPAIGN_RESULTS'

export const CREATE_PRODUCT = 'CREATE_PRODUCT'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const CREATE_HOSTED_SITE = 'CREATE_HOSTED_SITE'
export const UPDATE_HOSTED_SITE = 'UPDATE_HOSTED_SITE'

export const UPDATE_PENDINGS = 'UPDATE_PENDINGS'

export const SET_AUTH_MODAL = 'SET_AUTH_MODAL'
